In [1]:
import numpy as np

In [2]:
myList = [1,2,3,4,5]
myArray = np.array(myList)
print(type(myArray))
print(myArray)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [3]:
import numpy as np
b=np.arange(0,10,1)
print(b)

[0 1 2 3 4 5 6 7 8 9]


<h1>Numpy Functions</h1> 

In [4]:
npA2 = np.zeros(5)
print(npA2)

[0. 0. 0. 0. 0.]


<h2> zeros </h2>

In [5]:
npA2 = np.zeros((2,2))
print(npA2)

[[0. 0.]
 [0. 0.]]


<h2> Ones() </h2>

In [6]:
npA2 = np.ones((2,2))
print(npA2)

[[1. 1.]
 [1. 1.]]


In [7]:
npA2 = np.ones((2,2))
print(npA2[0][0])

1.0


<h2> eye() </h2>

In [8]:
b = np.eye(3)
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
c=np.linspace(0,1,11)
print(c)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


<h1>Numpy Properties </h1>

<h2> shape </h2>

In [10]:
d=np.ones((5,4))
print(d.shape)

(5, 4)


<h2> dtype </h2>

In [11]:
myarray=np.array([2,3,32,7])
print(myarray.dtype)

int64


<h2> reshape(n) </h2>

In [12]:
a = np.arange(1,126,1)
a = a.reshape(5,5,5)
print(a)

[[[  1   2   3   4   5]
  [  6   7   8   9  10]
  [ 11  12  13  14  15]
  [ 16  17  18  19  20]
  [ 21  22  23  24  25]]

 [[ 26  27  28  29  30]
  [ 31  32  33  34  35]
  [ 36  37  38  39  40]
  [ 41  42  43  44  45]
  [ 46  47  48  49  50]]

 [[ 51  52  53  54  55]
  [ 56  57  58  59  60]
  [ 61  62  63  64  65]
  [ 66  67  68  69  70]
  [ 71  72  73  74  75]]

 [[ 76  77  78  79  80]
  [ 81  82  83  84  85]
  [ 86  87  88  89  90]
  [ 91  92  93  94  95]
  [ 96  97  98  99 100]]

 [[101 102 103 104 105]
  [106 107 108 109 110]
  [111 112 113 114 115]
  [116 117 118 119 120]
  [121 122 123 124 125]]]


<h1> ~:Numpy Code With Harry:~ </h1>

<h1>Array Making Methods</h1>

<h3>1) Conversion from other python structure. </h3>

In [13]:
listArray = np.array([1,2,3])
listArray.shape

(3,)

In [14]:
listArray.dtype

dtype('int64')

In [15]:
listArray.size

3

In [16]:
np.array({34,32,12})

array({32, 34, 12}, dtype=object)

<h3>2) intrinsic numpy array creation objects. </h3>

In [17]:
zeros = np.zeros((2,5))
zeros.size

10

In [18]:
rng = np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

<h2> linspace(start,stop,num) </h2>

In [19]:
lspace = np.linspace(1,50,9)
lspace

array([ 1.   ,  7.125, 13.25 , 19.375, 25.5  , 31.625, 37.75 , 43.875,
       50.   ])

<h2> empty(n) </h2>

In [20]:
emp = np.empty((4,6))

In [21]:
emp

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

<h2> identity(n) / eye(n) </h2>

In [22]:
iden = np.identity(3)
print(iden)
print()
ey =np.eye(45)
print(ey)

#both are same

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [23]:
arr = np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [24]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

<h2> matrix axis Summation </h2>

In [25]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

<h2> sum </h2>

In [26]:
ar.sum(axis=0)

array([12,  8,  9])

In [27]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [28]:
ar.T # for matrix Transpose row ->

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [29]:
ar.sum(axis=1)

array([ 6, 15,  8])

<h2> T (transpose row to column and column to rorw) </h2>

In [30]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [31]:
ar.flat

In [32]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [33]:
ar.ndim

2

<h2> nbytes </h2>

In [34]:
ar.nbytes

72

<h2> argmax(), argmin(), argsort() </h2>

In [35]:
one = np.array([1,3,4,634,2])
print(one.argmax()) #index of large element in array
print(one.argmin()) #index of small element in array
print(one.argsort()) #print sorted list ordered element index

3
0
[0 4 1 2 3]


In [36]:
ar.argmax(axis=0)

array([2, 1, 1])

In [37]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [38]:
ar.argmax(axis=1)

array([2, 2, 0])

<h2> ravel() </h2>

In [39]:
ar.ravel()  #for convert Multidimensional array to 1-D array

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [40]:
ar2 = np.array([[1,2,1],
       [2,3,4],
       [5,4,2]])

In [41]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [42]:
ar2

array([[1, 2, 1],
       [2, 3, 4],
       [5, 4, 2]])

In [43]:
ar * ar2 

array([[ 1,  4,  3],
       [ 8, 15, 24],
       [35,  4,  0]])

In [44]:
[22,24] + [23,12]

[22, 24, 23, 12]

In [45]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

<h2> sqrt() </h2>

In [46]:
np.sqrt([1,2,3,4])

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [47]:
zero = np.zeros((3,4), dtype=int)  # for int value (by default dtype=float)
one = np.ones((3,4),dtype=int) # for int 1 value  (by default dtype=float)
string = np.ones((3,4),dtype=str) # for float value  (by default dtype=float)
string

array([['1', '1', '1', '1'],
       ['1', '1', '1', '1'],
       ['1', '1', '1', '1']], dtype='<U1')

In [48]:
emp = np.empty((3,4))
emp

array([[0.00000000e+000, 1.00937611e-320, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 8.60952352e-072, 4.22756205e-090,
        7.49401138e-067],
       [8.25998225e-072, 4.55798291e-037, 3.99910963e+252,
        1.03437590e+295]])

<h2> flatten() </h2>

In [49]:
ar.flatten()
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

<h2> transpose() / T (convert row to column nd column to row)</h2>

In [50]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [51]:
ar.transpose()

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

<h1> Mathematical operation using numpy </h1>

In [52]:
import numpy as np

In [53]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(1,10).reshape(3,3)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [54]:
arr1 + arr2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [55]:
np.add(arr1,arr2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [56]:
arr1 - arr2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [57]:
np.subtract(arr1,arr2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [58]:
arr1 / arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [59]:
np.divide(arr1,arr2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [60]:
arr1 * arr2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [61]:
np.multiply(arr2,arr1)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [62]:
arr1 @ arr2 # metrix multiplication to arr1 with arr2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [63]:
arr1.dot(arr2) # dot profuct of arr1 with arr2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [64]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
arr1.max()

9

In [66]:
arr1.max(axis=0) #columnm axis=0

array([7, 8, 9])

In [67]:
arr1.min()

1

In [68]:
arr1.min(axis=1) # row axis=1

array([1, 4, 7])

In [69]:
arr1.argmax()

8

In [70]:
arr1.argmin()

0

In [71]:
arr1.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [72]:
arr1.sum()

45

In [73]:
arr1.sum(axis=0)

array([12, 15, 18])

In [74]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [75]:
np.std(arr1)

2.581988897471611

In [76]:
np.exp(arr1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [77]:
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [78]:
np.log10(arr1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

<h1> python numpy Array Slicing(:) </h1>

In [79]:
a= np.arange(1,101).reshape(10,10)

In [80]:
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [81]:
a[0,0] # Particular element 

1

In [82]:
a[0].ndim #which n-d array


1

In [83]:
a[0,:] #a[row(start,end),column(start,end)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [84]:
a[:,0:1]

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [85]:
a[:,0:1].ndim

2

In [86]:
a[1:4,1:4]

array([[12, 13, 14],
       [22, 23, 24],
       [32, 33, 34]])

In [87]:
a[:,1:3]

array([[ 2,  3],
       [12, 13],
       [22, 23],
       [32, 33],
       [42, 43],
       [52, 53],
       [62, 63],
       [72, 73],
       [82, 83],
       [92, 93]])

In [88]:
a[:] # whole matrix

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [89]:
a[::] # whole matrix 

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [90]:
a.itemsize

8

In [91]:
a.dtype

dtype('int64')

<h1>Python Numpy Array Concatenation and Split </h1>

In [92]:
import numpy as np

In [93]:
arr1=np.arange(1,17).reshape(4,4)
arr2=np.arange(17,33).reshape(4,4)
print(arr1)
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [94]:
list1=[2,3,4]
list2=[5,6,7]
list1 + list2

[2, 3, 4, 5, 6, 7]

In [95]:
np.concatenate((arr1,arr2)) #concatenate both array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [96]:
np.concatenate((arr1,arr2), axis=1) #row wise concatenate

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [97]:
np.concatenate((arr1,arr2), axis=0) #column wise concatenate

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [98]:
np.vstack((arr1,arr2)) #column wise concatenation

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [99]:
np.hstack((arr1,arr2)) # row wise concatenation

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [100]:
np.hstack((arr1,arr2,arr1,arr2))

array([[ 1,  2,  3,  4, 17, 18, 19, 20,  1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24,  5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28,  9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32, 13, 14, 15, 16, 29, 30, 31, 32]])

In [101]:
np.split(arr1,2) # split(array,how_many_part) type = list

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [102]:
list1 = np.split(arr1,2)
type(list1) 

list

In [103]:
type(list1[0]) #type of list[0]

numpy.ndarray

In [104]:
np.split(arr1,2,axis=1) # split in row of array

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [105]:
d1=np.array([4,7,1,2,3])

In [106]:
d1

array([4, 7, 1, 2, 3])

In [107]:
np.split(d1,[1,2]) # n differnt part of array for split

[array([4]), array([7]), array([1, 2, 3])]