In [1]:
import numpy as np
import pandas as pd

In [2]:
np.random.seed(121)
data = np.random.randint(1,100,(5,4))
data

array([[67, 86,  9, 96],
       [66, 53, 84, 97],
       [47, 35, 53, 61],
       [55,  4, 95, 53],
       [58, 76, 89, 40]])

In [3]:
subjects = ['PDS','CN','ADA','SE']

In [4]:
rollno = np.arange(101,106)
rollno

array([101, 102, 103, 104, 105])

In [5]:
stu = pd.DataFrame(data,rollno,subjects)

In [6]:
stu>35

PDS     CN    ADA    SE
101  True   True  False  True
102  True   True   True  True
103  True  False   True  True
104  True  False   True  True
105  True   True   True  True

In [7]:
tempdf = stu>35

In [8]:
stu[tempdf]

PDS    CN   ADA  SE
101   67  86.0   NaN  96
102   66  53.0  84.0  97
103   47   NaN  53.0  61
104   55   NaN  95.0  53
105   58  76.0  89.0  40

<h1>setting / resetting index</h1>

In [9]:
stu.reset_index()
stu.index.name = "Roll no"
stu

PDS  CN  ADA  SE
Roll no                  
101       67  86    9  96
102       66  53   84  97
103       47  35   53  61
104       55   4   95  53
105       58  76   89  40

In [10]:
# for make ADA index

stu.set_index("ADA")

PDS  CN  SE
ADA             
9     67  86  96
84    66  53  97
53    47  35  61
95    55   4  53
89    58  76  40

In [11]:
stu.reset_index()

Roll no  PDS  CN  ADA  SE
0      101   67  86    9  96
1      102   66  53   84  97
2      103   47  35   53  61
3      104   55   4   95  53
4      105   58  76   89  40

In [12]:
stu

PDS  CN  ADA  SE
Roll no                  
101       67  86    9  96
102       66  53   84  97
103       47  35   53  61
104       55   4   95  53
105       58  76   89  40

In [13]:
stu.reset_index(inplace=True)

In [14]:
stu

Roll no  PDS  CN  ADA  SE
0      101   67  86    9  96
1      102   66  53   84  97
2      103   47  35   53  61
3      104   55   4   95  53
4      105   58  76   89  40

In [15]:
stu.index.name ="ADA"

In [16]:
stu

Roll no  PDS  CN  ADA  SE
ADA                           
0        101   67  86    9  96
1        102   66  53   84  97
2        103   47  35   53  61
3        104   55   4   95  53
4        105   58  76   89  40

In [25]:
df = pd.read_csv("MultiIndexDemo.csv")
df

Col Dep  Sem   RN    S1    S2    S3
0      ABC  CE    5  101  56.0  56.0  56.0
1      ABC  CE    5  102  54.0  54.0  54.0
2      ABC  CE    7  101  43.0  43.0  43.0
3      ABC  ME    5  101  38.0  38.0  38.0
4      ABC  ME    5  102  31.5  31.5  31.5
5  Darshan  CE    5  101  25.0  25.0  25.0
6  Darshan  CE    5  102  18.5  18.5  18.5
7  Darshan  CE    7  101  12.0  12.0  12.0
8  Darshan  ME    5  101   5.5   5.5   5.5

In [27]:
df.set_index(['Col','Dep','Sem','RN'],inplace=True)

In [21]:
df

S1    S2    S3
Col     Dep Sem RN                   
ABC     CE  5   101  56.0  56.0  56.0
                102  54.0  54.0  54.0
            7   101  43.0  43.0  43.0
        ME  5   101  38.0  38.0  38.0
                102  31.5  31.5  31.5
Darshan CE  5   101  25.0  25.0  25.0
                102  18.5  18.5  18.5
            7   101  12.0  12.0  12.0
        ME  5   101   5.5   5.5   5.5

In [24]:
df.loc['ABC','CE',5,102]

S1    54.0
S2    54.0
S3    54.0
Name: (ABC, CE, 5, 102), dtype: float64

In [29]:
hf = pd.read_csv("MultiIndexDemo.csv",index_col=[0,1,2,3])
hf

S1    S2    S3
Col     Dep Sem RN                   
ABC     CE  5   101  56.0  56.0  56.0
                102  54.0  54.0  54.0
            7   101  43.0  43.0  43.0
        ME  5   101  38.0  38.0  38.0
                102  31.5  31.5  31.5
Darshan CE  5   101  25.0  25.0  25.0
                102  18.5  18.5  18.5
            7   101  12.0  12.0  12.0
        ME  5   101   5.5   5.5   5.5

In [52]:
np.random.seed(121)
data=np.random.randint(1,100,25).reshape(5,5)
data

array([[67, 86,  9, 96, 66],
       [53, 84, 97, 47, 35],
       [53, 61, 55,  4, 95],
       [53, 58, 76, 89, 40],
       [22, 42, 56, 84, 95]])

In [53]:
i=[101,102,103,104,105]

In [54]:
c = ['a','b','c','d','e']

In [55]:
d = pd.DataFrame(data,i,c)
d

a   b   c   d   e
101  67  86   9  96  66
102  53  84  97  47  35
103  53  61  55   4  95
104  53  58  76  89  40
105  22  42  56  84  95

In [64]:
f = d[d>35]
f

a   b     c     d     e
101  67.0  86   NaN  96.0  66.0
102  53.0  84  97.0  47.0   NaN
103  53.0  61  55.0   NaN  95.0
104  53.0  58  76.0  89.0  40.0
105   NaN  42  56.0  84.0  95.0

In [65]:
f.dropna()

a   b     c     d     e
104  53.0  58  76.0  89.0  40.0

In [67]:
f

a   b     c     d     e
101  67.0  86   NaN  96.0  66.0
102  53.0  84  97.0  47.0   NaN
103  53.0  61  55.0   NaN  95.0
104  53.0  58  76.0  89.0  40.0
105   NaN  42  56.0  84.0  95.0

In [72]:
f.fillna("35")

a   b     c     d     e
101  67.0  86    35  96.0  66.0
102  53.0  84  97.0  47.0    35
103  53.0  61  55.0    35  95.0
104  53.0  58  76.0  89.0  40.0
105    35  42  56.0  84.0  95.0

In [80]:
f.interpolate(limit_direction='backward')

a   b     c     d     e
101  67.0  86  97.0  96.0  66.0
102  53.0  84  97.0  47.0  80.5
103  53.0  61  55.0  68.0  95.0
104  53.0  58  76.0  89.0  40.0
105   NaN  42  56.0  84.0  95.0

In [81]:
f.interpolate(limit=90)

a   b     c     d     e
101  67.0  86   NaN  96.0  66.0
102  53.0  84  97.0  47.0  80.5
103  53.0  61  55.0  68.0  95.0
104  53.0  58  76.0  89.0  40.0
105  53.0  42  56.0  84.0  95.0

In [103]:
ah = pd.read_excel("Studentdata.xlsx",index_col=[0,1,2,3])

In [104]:
ah

SPI
Col     Dep Sem RN      
ABC     CE  5   101  9.3
                102  4.3
                103  3.4
            7   101  3.5
                102  3.4
        EE  5   101  5.6
                102  6.7
            7   101  5.6
        IT  5   101  5.5
            7   101  4.4
Darshan IT  5   101  9.9
            7   101  8.1
        CE  5   101  9.7
                102  8.1
            7   101  9.4
        EE  5   101  8.1
                102  9.2
                103  8.2
            7   101  9.1
                102  8.1

In [105]:
ah.xs("EE",axis=0,level='Dep')

SPI
Col     Sem RN      
ABC     5   101  5.6
            102  6.7
        7   101  5.6
Darshan 5   101  8.1
            102  9.2
            103  8.2
        7   101  9.1
            102  8.1

In [112]:
ah.xs("cE",axis=0,level='Dep')[ah>=7.5][102].dropn

KeyError: 'cE'